apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: flaskapp:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "150Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
